### ISSUE TITLE
Remove local codewind projects action does not visually indicate project removed

### ISSUE THREAD

**Issue by ericdylanpeters2** [eclipse/codewind-eclipse#102]
When I select the 'Remove' action from a project in the codewind explorer view, it does not get removed in the view (if I select Refresh from the Local Projects node only then does it show as having been removed).

Seems this occurring for all project types (MAC OS 10.14.5 ).

**Comment by eharris369** [comment]
One thing I have noticed is that if the view is not showing, it does not get updated which is not good.  For example if I start a build on a project and then switch to the Console view and wait a while, then switch back to the Codewind Explorer view it is still in Stopped/Building state and I have to refresh to get the correct state.  Could be in the way the refresh is being done?

**Comment by eharris369** [comment]
I can't actually reproduce the problem where the view does not update if not visible anymore so maybe it was just a random glitch in Eclipse.

**Comment by eharris369** [comment]
I do still see the original problem of the project not being removed from the view so this issue should stay open.

**Comment by eharris369** [comment]
This has been fixed by PR https://github.com/eclipse/codewind-eclipse/pull/495
