### ISSUE TITLE
Codewind project icon in Debug view is pixelated / blobby 

### ISSUE THREAD

**Issue by ericdylanpeters2** [eclipse/codewind-eclipse#103]
Icons for codewind projects look fine everywhere else, but show as pixelated / blobby in the Debug view (see below). Could be a problem on MAC only.

![image](https://user-images.githubusercontent.com/48959948/60125770-7eb2ab00-975a-11e9-8821-4fd5e13287db.png)

**Comment by eharris369** [comment]
The icon looks fine on Windows and Linux (RedHat) so it must be MAC specific.

**Comment by eharris369** [comment]
I tried this on another MAC machine and the icon was fine there too.

**Comment by ericdylanpeters2** [comment]
I’ll install the latest driver and reopen if still a problem.

**Comment by ericdylanpeters2** [comment]
@eharris369 I updated to latest driver and no longer see the issue.
