### ISSUE TITLE
Read timeouts when creating multiple projects from eclipse plugin

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind-eclipse#104]
I got the latest eclipse plugin and tried to create projects, when creating lagom and node projects and I got read timeouts. Initially I was able to create go and java projects and those projects built successfully. 

This should be fixed for the upcoming milestone driver, please add stopship tag.

Here are the logs and screenshot from the failures..

[.log](https://github.com/eclipse/codewind-eclipse/files/3328353/default.log)

![ReadTimeOut](https://user-images.githubusercontent.com/713849/60153499-68d0d480-97b2-11e9-95df-7ad27b05cd66.JPG)

**Comment by eharris369** [comment]
This problem occurred with the last Codewind tech preview and only with project create requests to PFE.  It was never a problem with microclimate even though the IDE is not doing anything different except calling the new API for Codewind.

**Comment by jagraj** [comment]
with the latest plugin, I no longer see this problem. Thx for the fix.
