### ISSUE TITLE
Install failed from eclipse plugin but logs does not show where the failure is.

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind-eclipse#106]
I tried to Install Codewind from eclipse plugin, my install was keep on failing on Windows due to docker volume mount issues. I was looking for failure in the logs and it was not giving any information about the failure, all it printed in the log with this message. 

```
!ENTRY org.eclipse.codewind.ui 4 0 2019-06-25 21:54:33.161
!MESSAGE There was a problem trying to start Codewind: 
```

Log
[.log](https://github.com/eclipse/codewind-eclipse/files/3329916/default.log)

I had to Install Codewind outside of eclipse tools to find out why this was keep failing. Here is the failure below and this output was missing in the .log file.

Here is the output that I got from installer in the console but not in the tools.

```
.\codewind.exe start
==> created file installer-docker-compose.yaml
==> environment structure written to installer-docker-compose.yaml
System architecture is:  amd64
Host operating system is:  windows
Please wait whilst containers initialize...
Creating network "codewind_network" with the default driver
Creating codewind-performance ...
[1Bting codewind-performance ... [31merror[0m
ERROR: for codewind-performance  Cannot start service codewind-performance: b"error while creating mount source path '/host_mnt/c/codewind-workspace': mkdir /host_mnt/c: file exists"

ERROR: for codewind-performance  Cannot start service codewind-performance: b"error while creating mount source path '/host_mnt/c/codewind-workspace': mkdir /host_mnt/c: file exists"
Encountered errors while bringing up the project.
==> finished deleting file installer-docker-compose.yaml
```

**Comment by eharris369** [comment]
I suspect the installer is sending its messages to system out instead of system error.  The IDE is logging the system error output.  It is easy enough to log the system out from the installer on a failure as well though the installer should be sending errors to system error.
