### ISSUE TITLE
[Windows 10] Application Monitor Window does not present data in Eclipse, but it does in the browser

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind-eclipse#115]
**Environment:**
- **Codewind version:** Latest Development Version (codewind-0.2.0-201906261508.zip)
- **Eclipse version:** 2019-06 (4.12.0)
- **OS:** VM with Windows 10

**Description:**
Application Monitor window does not present data in Eclipse, but it does in the browser.

![Screen Shot 2019-06-26 at 3 36 28 PM](https://user-images.githubusercontent.com/49531960/60210570-2ac3c700-982b-11e9-879a-41bc36ea2c21.png)

![Screen Shot 2019-06-26 at 3 37 13 PM](https://user-images.githubusercontent.com/49531960/60210577-30211180-982b-11e9-8601-53b0a9facc90.png)

**Steps:**
1. Install and start the Codewind plugin for Eclipse
2. Create a project (i.e. Java MicroProfile)
3. Right click on the created project
4. Click on "Open Application Monitor"

@jagraj

**Comment by eharris369** [comment]
This will be fixed by #111 as well.
