### ISSUE TITLE
Codewind forces users to launch the Eclipse on the codewind-workspace folder

### ISSUE THREAD

**Issue by keithchong** [eclipse/codewind-eclipse#166]
It's not necessarily a defect, but a usability/design problem.

Here's the issue:

Start with Java EPP package in any new workspace folder, and then install the Codewind IDE plugin and Codewind PFE (by double click install).

Import a project into the workspace.  Right click on the project and select Codewind->Add Project
--> Error message will appear, saying that the project is not located in the Codewind workspace.

**Comment by eharris369** [comment]
This is a limitation of Codewind which requires projects to be in the workspace.
