### ISSUE TITLE
Eclipse IDE: In the Project Overview page, the project type is Unknown for any extension projects

### ISSUE THREAD

**Issue by keithchong** [eclipse/codewind-eclipse#217]
**Codewind version:** Dev driver (but it isn't the problem since the specific extension project type shows up in the NewCodewindProjectWizard)
**OS:**  Mac

**IDE extension version:** Eclipse IDE Plugin latest from master

**Description:**  Using Codewind for Eclipse, in the project overview page, the project type for any extension project shows up as Unknown

![Screen Shot 2019-08-14 at 1 00 27 PM](https://user-images.githubusercontent.com/7726022/63041010-d6d17800-be94-11e9-9eb8-4309cacbe163.png)

See related, for VS Code:  https://github.com/eclipse/codewind-vscode/issues/67

**Comment by makandre** [comment]
A minor thing but I notice the type is now `appsodyExtension`, whereas in vscode it would display as `Appsody`.

The fix for https://github.com/eclipse/codewind-vscode/issues/67 had some logic added to take only the first word and capitalize it I believe.

**Comment by tetchel** [comment]
i opened a new issue for that
