### ISSUE TITLE
Pass language from template to bind endpoint

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind-eclipse#34]
Fix for (internal issue link) https://github.ibm.com/dev-ex/portal/issues/1029

In the create-from-template case, instead of passing the language we get from `/validate`, we should pass the language from the template. this means we will use the correct language regardless of if the initialize container can detect it or not.

**Comment by eharris369** [comment]
For the template case, the code is already passing in the language from the template.  The template API now returns the project type as well though so I will use this issue to fix that up.  This is for the template case only.  The add existing project case is more work so I will do that in another issue.

**Comment by eharris369** [comment]
Fixed by PR #35
