### ISSUE TITLE
New Codewind Connection and Project Wizard names should not include "New"

### ISSUE THREAD

**Issue by keithchong** [eclipse/codewind-eclipse#48]
The New Codewind Wizards should be renamed

The convention is that you just use the 'name of the object that you are creating.  See screencap for comparison with other wizards.

<img width="615" alt="Screen Shot 2019-06-17 at 11 49 16 AM" src="https://user-images.githubusercontent.com/7726022/59618732-d61ba000-90f6-11e9-824f-6409d09441f6.png">

**Comment by eharris369** [comment]
Fixed by PR #101
